# config.py

# --- Торговые Параметры ---
DEFAULT_MAX_CONCURRENT_TRADES = 3
DEFAULT_STOP_LOSS_PERCENT = 1  # 
DEFAULT_TAKE_PROFIT_PERCENT = 3  # %
MIN_PRICE_DIFF_PERCENT = 0 # Минимальная разница в 1%

STOP_LOSS_MODE = 'ATR'  # Режим установки стоп-лосса. Варианты: 'ATR' или 'PERCENT'
DEFAULT_ATR_MULTIPLIER = 3.0    # Множитель N для ATR. Стоп = цена входа - (N * ATR)


# ---  ТРЕЙЛИНГ-СТОП ---
USE_TRAILING_STOP = True # True, чтобы использовать трейлинг-стоп вместо тейк-профита
TRAILING_STOP_ACTIVATION_PERCENT = 1  # Цена должна вырасти на 1.0%, чтобы трейлинг активировался

# --- Симуляция Портфеля ---
SIMULATION_INITIAL_BALANCE = 1000.0  
TRADING_COMMISSION_PERCENT = 0.1  

# --- Telegram Настройки ---
TELEGRAM_BOT_TOKEN = "8442935176:AAEfMDKH7WsMycA1yxv0nv8QaGEaRsZ1b9E"
TELEGRAM_CHAT_ID = '-4992993900'

# --- API Ключи ---
BYBIT_API_KEY = 'bKyNioyok1HbaJXzuM'
BYBIT_API_SECRET = 'xXtHaJbZFNyFOA8SKDx3svBXH9aEbacqRlNm'

my_symbols = [
    '0GUSDT', '1INCHUSDT', '2ZUSDT', 'A8USDT', 'AAPLXUSDT', 
    'AAVEUSDT', 'ACHUSDT', 'ACSUSDT', 'ADAUSDT', 'AEROUSDT', 
    'AEVOUSDT', 'AFCUSDT', 'AGIUSDT', 'AGLDUSDT',  
    'AIOZUSDT', 'AIXBTUSDT', 'ALCHUSDT', 'ALGOUSDT', 'ALTUSDT', 
    'AMIUSDT', 'AMZNXUSDT', 'ANIMEUSDT', 'ANKRUSDT', 'AOUSDT', 
    'APEUSDT', 'APEXUSDT', 'APTUSDT', 'ARBUSDT', 'ARKMUSDT', 
    'ARTUSDT', 'ARTYUSDT', 'ARUSDT', 'ASRRUSDT', 'ASTERUSDT', 
    'ATHUSDT', 'ATOMUSDT', 'AURORAUSDT', 'AUSDT', 'AVAILUSDT', 
    'AVAUSDT', 'AVAXUSDT', 'AVLUSDT', 'AVNTUSDT', 'AXLUSDT', 
    'AXSUSDT', 'B3USDT', 'BABY1USDT', 'BABYDOGEUSDT', 'BANUSDT', 
    'BARDUSDT', 'BATUSDT', 'BBSOLUSDT', 'BBUSDT', 'BCHUSDT',
    'BDXNUSDT', 'BEAMUSDT', 'BELUSDT', 'BERAUSDT', 'BICOUSDT',
    'BLASTUSDT', 'BLURUSDT', 'BMTUSDT', 'BNBUSDT', 'BOBAUSDT',
    'BOMBUSDT', 'BOMEUSDT', 'BONKUSDT', 'BRETTUSDT', 'BRUSDT',
    'BTCUSDT', 'BTTUSDT', 'C98USDT', 'CAKEUSDT', 'CAMPUSDT',
    'CARVUSDT', 'CATIUSDT', 'CATUSDT', 'CBKUSDT', 'CELOUSDT',
    'CFGUSDT', 'CGPTUSDT', 'CHILLGUYUSDT', 'CHZUSDT', 'CITYUSDT',
    'CLOUDUSDT', 'CMETHUSDT', 'COINXUSDT', 'COMMONUSDT', 'COMPUSDT',
    'COOKIEUSDT', 'COOKUSDT', 'COQUSDT', 'COREUSDT', 'CORNUSDT',
    'CPOOLUSDT', 'CRCLXUSDT', 'CRVUSDT', 'CSPRUSDT', 'CTAUSDT',
    'CTCUSDT', 'CUDISUSDT', 'CYBERUSDT', 'DAIUSDT', 'DBRUSDT',
    'DEEPUSDT', 'DEGENUSDT', 'DGBUSDT', 'DIAMUSDT', 'DMAILUSDT',
    'DOGEUSDT', 'DOGSUSDT', 'DOLOUSDT', 'DOODUSDT', 'DOTUSDT',
    'DRIFTUSDT', 'DYDXUSDT', 'DYMUSDT', 'EATUSDT', 'EGLDUSDT',
    'EIGENUSDT', 'ELDEUSDT', 'ELXUSDT', 'ENAUSDT', 'ENJUSDT',
    'ENSOUSDT', 'ENSUSDT', 'EPTUSDT', 'ERAUSDT', 'ESEUSDT',
    'ESUSDT', 'ETCUSDT', 'ETHFIUSDT', 'ETHUSDT', 'ETHWUSDT',
    'FETUSDT', 'FFUSDT', 'FHEUSDT', 'FIDAUSDT', 'FILUSDT',
    'FITFIUSDT', 'FLIPUSDT', 'FLOCKUSDT', 'FLOKIUSDT', 'FLOWUSDT',
    'FLRUSDT', 'FLUIDUSDT', 'FORTUSDT', 'FOXYUSDT', 'FRAGUSDT',
    'FTTUSDT', 'FUELUSDT', 'FUSDT', 'FXSUSDT', 'G3USDT',
    'GALAUSDT', 'GAMEUSDT', 'GLMRUSDT', 'GMTUSDT', 'GMXUSDT',
    'GOATUSDT', 'GODSUSDT', 'GOOGLXUSDT', 'GPSUSDT', 'GRASSUSDT',
    'GRTUSDT', 'GTAIUSDT', 'GUSDT', 'HAEDALUSDT', 'HBARUSDT',
    'HFTUSDT', 'HMSTRUSDT', 'HNTUSDT', 'HOLOUSDT', 'HOMEUSDT',
    'HOODXUSDT', 'HOOKUSDT', 'HPOS10IUSDT', 'HTXUSDT', 'HUMAUSDT',
    'HUSDT', 'HYPERUSDT', 'HYPEUSDT', 'ICNTUSDT', 'ICPUSDT',
    'ICXUSDT', 'IDUSDT', 'IMXUSDT', 'INITUSDT', 'INJUSDT',
    'INSPUSDT', 'INTERUSDT', 'IOUSDT', 'IPUSDT', 'IZIUSDT',
    'JASMYUSDT', 'JEFFUSDT', 'JSTUSDT', 'JTOUSDT', 'JUPUSDT',
    'JUSDT', 'JUVUSDT', 'KAIAUSDT', 'KASTAUSDT', 'KASUSDT',
    'KAVAUSDT', 'KCSUSDT', 'KILOUSDT', 'KMNOUSDT', 'KSMUSDT',
    'KUBUSDT', 'KUSDT', 'L3USDT', 'LADYSUSDT', 'LAUSDT',
    'LAVAUSDT', 'LAYERUSDT', 'LBTCUSDT', 'LDOUSDT', 'LINEAUSDT',
    'LINKUSDT', 'LITKEYUSDT', 'LLUSDT', 'LMWRUSDT', 'LOOKSUSDT',
    'LRCUSDT', 'LTCUSDT', 'LUNAIUSDT', 'LUNAUSDT', 'LUNCUSDT',
    'MAGICUSDT', 'MAJORUSDT', 'MANAUSDT', 'MANTAUSDT', 'MASAUSDT',
    'MASKUSDT', 'MAVIAUSDT', 'MBOXUSDT', 'MBXUSDT', 'MCDXUSDT',
    'MCRTUSDT', 'MDAOUSDT', 'MEEUSDT', 'MEMEFIUSDT', 'MEMEUSDT',
    'MERLUSDT', 'METAXUSDT', 'METHUSDT', 'METUSDT', 'MEUSDT',
    'MEWUSDT', 'MILKUSDT', 'MINAUSDT', 'MMTUSDT', 'MNTUSDT',
    'MOCAUSDT', 'MODEUSDT', 'MOGUSDT', 'MONPROUSDT', 'MORPHOUSDT',
    'MOVEUSDT', 'MOVRUSDT', 'MPLXUSDT', 'MVLUSDT', 'MVUSDT',
    'MXUSDT', 'MYRIAUSDT', 'MYROUSDT', 'NAKAUSDT', 'NAVXUSDT',
    'NEARUSDT', 'NEIROCTOUSDT', 'NEONUSDT', 'NEWTUSDT', 'NEXOUSDT',
    'NFTUSDT', 'NIBIUSDT', 'NOMUSDT', 'NOTUSDT', 'NRNUSDT',
    'NSUSDT', 'NVDAXUSDT', 'NXPCUSDT', 'NYMUSDT', 'OASUSDT',
    'OBOLUSDT', 'OBTUSDT', 'ODOSUSDT', 'OLUSDT', 'OMUSDT',
    'ONDOUSDT', 'ONEUSDT', 'OPUSDT', 'ORDERUSDT', 'ORDIUSDT',
    'PAALUSDT', 'PARTIUSDT', 'PELLUSDT', 'PENDLEUSDT',
    'PENGUUSDT', 'PEOPLEUSDT', 'PEPEUSDT', 'PERPUSDT', 'PINEYEUSDT',
    'PIRATEUSDT', 'PLUMEUSDT', 'PNUTUSDT', 'POLUSDT', 'PONKEUSDT',
    'POPCATUSDT', 'PORT3USDT', 'PORTALSUSDT', 'PORTALUSDT', 'PRCLUSDT',
    'PRIMEUSDT', 'PROVEUSDT', 'PSGUSDT', 'PSTAKEUSDT', 'PUFFERUSDT',
    'PUFFUSDT', 'PUMPBTCUSDT', 'PUMPUSDT', 'PURSEUSDT', 'PYTHUSDT',
    'PYUSDUSDT', 'QNTUSDT', 'QORPOUSDT', 'QTUMUSDT', 'RACAUSDT',
    'RATSUSDT', 'RDNTUSDT', 'RECALLUSDT', 'REDUSDT', 'RENDERUSDT',
    'RESOLVUSDT', 'RLUSDUSDT', 'ROAMUSDT', 'ROOTUSDT', 'ROSEUSDT',
    'RPLUSDT', 'RSS3USDT', 'RUNEUSDT', 'RVNUSDT', 'SAFEUSDT',
    'SAHARAUSDT', 'SANDUSDT', 'SAROSUSDT', 'SATSUSDT', 'SCAUSDT',
    'SCRTUSDT', 'SCRUSDT', 'SCUSDT', 'SDUSDT', 'SEIUSDT',
    'SENDUSDT', 'SERAPHUSDT', 'SFUNDUSDT', 'SHARDSUSDT', 'SHIBUSDT',
    'SHRAPUSDT', 'SIDUSUSDT', 'SIGNUSDT', 'SISUSDT', 'SKATEUSDT',
    'SKYUSDT', 'SLPUSDT', 'SNXUSDT', 'SOLOUSDT', 'SOLUSDT',
    'SOLVUSDT', 'SOMIUSDT', 'SONICUSDT', 'SOSOUSDT', 'SPECUSDT',
    'SPELLUSDT', 'SPKUSDT', 'SPXUSDT', 'SQDUSDT', 'SQRUSDT',
    'SSVUSDT', 'STETHUSDT', 'STREAMUSDT', 'STRKUSDT', 'STXUSDT',
    'SUIUSDT', 'SUNDOGUSDT', 'SUNUSDT', 'SUPRAUSDT', 'SUSDT',
    'SUSHIUSDT', 'SVLUSDT', 'SWEATUSDT', 'SWELLUSDT', 'SXTUSDT',
    'SYNDUSDT', 'TACUSDT', 'TAIKOUSDT', 'TAIUSDT', 'TAUSDT',
    'TELUSDT', 'THETAUSDT', 'TIAUSDT', 'TIMEUSDT', 'TNSRUSDT',
    'TOKENUSDT', 'TONUSDT', 'TOSHIUSDT', 'TOWNSUSDT', 'TRCUSDT',
    'TREEUSDT', 'TRUMPUSDT', 'TRVLUSDT', 'TRXUSDT', 'TSLAXUSDT',
    'TUNAUSDT', 'TURBOSUSDT', 'TUSDUSDT', 'TWTUSDT', 'ULTIUSDT',
    'UMAUSDT', 'UNIUSDT', 'USD1USDT', 'USDDUSDT',
    'USDEUSDT', 'USDTBUSDT', 'USDYUSDT',
    'USTCUSDT', 'UUSDT', 'UXLINKUSDT', 'VANAUSDT', 'VANRYUSDT',
    'TUNAUSDT', 'TURBOSUSDT', 'TWTUSDT', 'ULTIUSDT',
    'UMAUSDT', 'UNIUSDT', 'USD1USDT', 'USDCUSDT', 'USDDUSDT',
    'USDEUSDT', 'USDQUSDT', 'USDRUSDT', 'USDTBUSDT', 'USDYUSDT',
    'USTCUSDT', 'UUSDT', 'UXLINKUSDT', 'VANAUSDT', 'VANRYUSDT',
    'UMAUSDT', 'UNIUSDT', 'USD1USDT', 'USDCUSDT', 'USDDUSDT',
    'USDEUSDT', 'USDQUSDT', 'USDRUSDT', 'USDTBUSDT', 'USDYUSDT',
    'USTCUSDT', 'UUSDT', 'UXLINKUSDT', 'VANAUSDT', 'VANRYUSDT',
    'USDEUSDT', 'USDQUSDT', 'USDRUSDT', 'USDTBUSDT', 'USDYUSDT',
    'USTCUSDT', 'UUSDT', 'UXLINKUSDT', 'VANAUSDT', 'VANRYUSDT',
    'USTCUSDT', 'UUSDT', 'UXLINKUSDT', 'VANAUSDT', 'VANRYUSDT',
    'VELOUSDT', 'VENOMUSDT', 'VETUSDT', 'VICUSDT', 'VINUUSDT',
    'VIRTUALUSDT', 'VRAUSDT', 'VTHOUSDT', 'VVVUSDT', 'WALUSDT',
    'WAVESUSDT', 'WAXPUSDT', 'WCTUSDT', 'WEMIXUSDT',
    'WENUSDT', 'WIFUSDT', 'WLDUSDT', 'WLFIUSDT', 'WOOUSDT',
    'WUSDT', 'XAIUSDT', 'XANUSDT', 'XAUTUSDT', 'XAVAUSDT',
    'XCADUSDT', 'XDCUSDT', 'XEMUSDT', 'XIONUSDT',
    'XLMUSDT', 'XOUSDT', 'XPLUSDT', 'XRPUSDT', 'XTERUSDT',
    'XTZUSDT', 'XUSDT', 'XUSDUSDT', 'YBUSDT', 'YFIUSDT',
    'ZBTUSDT', 'ZENTUSDT', 'ZENUSDT', 'ZEREBROUSDT', 'ZETAUSDT',
    'ZEXUSDT', 'ZIGUSDT', 'ZILUSDT', 'ZKCUSDT', 'ZKJUSDT',
    'ZKLUSDT', 'ZKUSDT', 'ZORAUSDT', 'ZRCUSDT', 'ZROUSDT',
    'ZRXUSDT', 'ZTXUSDT'
]
