# config.py

# --- Telegram Настройки ---
TELEGRAM_TOKEN = "8442935176:AAEfMDKH7WsMycA1yxv0nv8QaGEaRsZ1b9E"
TELEGRAM_CHANNEL = '-4992993900'

# --- API Ключи ---
BYBIT_API_KEY = 'bKyNioyok1HbaJXzuM'
BYBIT_API_SECRET = 'xXtHaJbZFNyFOA8SKDx3svBXH9aEbacqRlNm'

# --- Торговые Параметры ---
MAX_CONCURRENT_TRADES = 3
STOP_LOSS_PERCENT = 1.5
TAKE_PROFIT_PERCENT = 3.0
my_symbols = [
    '0GUSDT', '1INCHUSDT', '2ZUSDT', 'A8USDT', 'AAPLXUSDT', 'AAVEUSDT', 'ACHUSDT', 'ACSUSDT',
    'ADAUSDT', 'AEROUSDT', 'AEVOUSDT', 'AFCUSDT', 'AFGUSDT', 'AGIUSDT', 'AGLDUSDT', 'AI16ZUSDT',
    'AIOZUSDT', 'AIXBTUSDT', 'AKIUSDT', 'ALCHUSDT', 'ALGOUSDT', 'ALTUSDT', 'AMIUSDT', 'AMZNXUSDT',
    'ANIMEUSDT', 'ANKRUSDT', 'AOUSDT', 'APEUSDT', 'APEXUSDT', 'APPUSDT', 'APTUSDT', 'ARBUSDT',
    'ARKMUSDT', 'ARTUSDT', 'ARTYUSDT', 'ARUSDT', 'ASRRUSDT', 'ASTERUSDT', 'ATHUSDT', 'ATOMUSDT',
    'AURORAUSDT', 'AUSDT', 'AVAILUSDT', 'AVAUSDT', 'AVAXUSDT', 'AVLUSDT', 'AVNTUSDT', 'AXLUSDT',
    'AXSUSDT', 'B3TRUSDT', 'B3USDT', 'BABY1USDT', 'BABYDOGEUSDT', 'BANUSDT', 'BARDUSDT', 'BATUSDT',
    'BBSOLUSDT', 'BBUSDT', 'BCHUSDT', 'BCUTUSDT', 'BDXNUSDT', 'BEAMUSDT', 'BELUSDT', 'BERAUSDT',
    'BICOUSDT', 'BLASTUSDT', 'BLURUSDT', 'BMTUSDT', 'BNBUSDT', 'BOBAUSDT', 'BOMBUSDT', 'BOMEUSDT',
    'BONKUSDT', 'BRETTUSDT', 'BRUSDT', 'BTCUSDT', 'BTTUSDT', 'C98USDT', 'CAKEUSDT', 'CAMPUSDT',
    'CARVUSDT', 'CATIUSDT', 'CATUSDT', 'CBKUSDT', 'CELOUSDT', 'CFGUSDT', 'CGPTUSDT', 'CHILLGUYUSDT',
    'CHZUSDT', 'CITYUSDT', 'CLOUDUSDT', 'CMETHUSDT', 'COAUSDT', 'COINXUSDT', 'COMMONUSDT', 'COMPUSDT',
    'COOKIEUSDT', 'COOKUSDT', 'COQUSDT', 'COREUSDT', 'CORNUSDT', 'CPOOLUSDT', 'CRCLXUSDT', 'CRVUSDT',
    'CSPRUSDT', 'CTAUSDT', 'CTCUSDT', 'CUDISUSDT', 'CYBERUSDT', 'DAIUSDT', 'DBRUSDT', 'DEEPUSDT',
    'DEFIUSDT', 'DEGENUSDT', 'DGBUSDT', 'DIAMUSDT', 'DMAILUSDT', 'DOGEUSDT', 'DOGSUSDT', 'DOLOUSDT',
    'DOMEUSDT', 'DOODUSDT', 'DOTUSDT', 'DRIFTUSDT', 'DUELUSDT', 'DYDXUSDT', 'DYMUSDT', 'EATUSDT',
    'EGLDUSDT', 'EGP1USDT', 'EIGENUSDT', 'ELDEUSDT', 'ELXUSDT', 'ENAUSDT', 'ENJUSDT', 'ENSOUSDT',
    'ENSUSDT', 'EPTUSDT', 'ERAUSDT', 'ESEUSDT', 'ESUSDT', 'ETCUSDT', 'ETHFIUSDT', 'ETHUSDT',
    'ETHWUSDT', 'EVERUSDT', 'FETUSDT', 'FFUSDT', 'FHEUSDT', 'FIDAUSDT', 'FILUSDT', 'FITFIUSDT',
    'FLIPUSDT', 'FLOCKUSDT', 'FLOKIUSDT', 'FLOWUSDT', 'FLRUSDT', 'FLUIDUSDT', 'FORTUSDT', 'FOXYUSDT',
    'FRAGUSDT', 'FTTUSDT', 'FUELUSDT', 'FUSDT', 'FXSUSDT', 'G3USDT', 'G7USDT', 'GALAUSDT',
    'GALFTUSDT', 'GAMEUSDT', 'GLMRUSDT', 'GMTUSDT', 'GMXUSDT', 'GOATUSDT', 'GODSUSDT', 'GOOGLXUSDT',
    'GPSUSDT', 'GRASSUSDT', 'GRTUSDT', 'GSWIFTUSDT', 'GTAIUSDT', 'GUSDT', 'HAEDALUSDT', 'HBARUSDT',
    'HFTUSDT', 'HMSTRUSDT', 'HNTUSDT', 'HOLOUSDT', 'HOMEUSDT', 'HOODXUSDT', 'HOOKUSDT', 'HPOS10IUSDT',
    'HTXUSDT', 'HUMAUSDT', 'HUSDT', 'HYPERUSDT', 'HYPEUSDT', 'ICNTUSDT', 'ICPUSDT', 'ICXUSDT',
    'IDUSDT', 'IMXUSDT', 'INITUSDT', 'INJUSDT', 'INSPUSDT', 'INTERUSDT', 'IOUSDT', 'IPUSDT',
    'IZIUSDT', 'JASMYUSDT', 'JEFFUSDT', 'JSTUSDT', 'JTOUSDT', 'JUPUSDT', 'JUSDT', 'JUVUSDT',
    'KAIAUSDT', 'KASTAUSDT', 'KASUSDT', 'KAVAUSDT', 'KCSUSDT', 'KILOUSDT', 'KMNOUSDT', 'KSMUSDT',
    'KUBUSDT', 'KUSDT', 'L3USDT', 'LADYSUSDT', 'LAUSDT', 'LAVAUSDT', 'LAYERUSDT', 'LBTCUSDT',
    'LDOUSDT', 'LFTUSDT', 'LINEAUSDT', 'LINKUSDT', 'LLUSDT', 'LMWRUSDT', 'LOOKSUSDT', 'LRCUSDT',
    'LTCUSDT', 'LUNAIUSDT', 'LUNAUSDT', 'LUNCUSDT', 'MAGICUSDT', 'MAJORUSDT', 'MANAUSDT', 'MANTAUSDT',
    'MASAUSDT', 'MASKUSDT', 'MAVIAUSDT', 'MBOXUSDT', 'MBXUSDT', 'MCDXUSDT', 'MCRTUSDT', 'MDAOUSDT',
    'MEEUSDT', 'MEMEFIUSDT', 'MEMEUSDT', 'MERLUSDT', 'METAXUSDT', 'METHUSDT', 'METUSDT', 'MEUSDT',
    'MEWUSDT', 'MILKUSDT', 'MINAUSDT', 'MNTUSDT', 'MOCAUSDT', 'MODEUSDT', 'MOGUSDT', 'MONPROUSDT',
    'MORPHOUSDT', 'MOVEUSDT', 'MOVRUSDT', 'MOZUSDT', 'MPLXUSDT', 'MVLUSDT', 'MVUSDT', 'MXUSDT',
    'MYRIAUSDT', 'MYROUSDT', 'NAKAUSDT', 'NAVXUSDT', 'NEARUSDT', 'NEIROCTOUSDT', 'NEONUSDT', 'NEWTUSDT',
    'NEXOUSDT', 'NFTUSDT', 'NIBIUSDT', 'NOMUSDT', 'NOTUSDT', 'NRNUSDT', 'NSUSDT', 'NVDAXUSDT',
    'NXPCUSDT', 'NYMUSDT', 'OASUSDT', 'OBOLUSDT', 'OBTUSDT', 'ODOSUSDT', 'OIKUSDT', 'OLUSDT',
    'OMUSDT', 'ONDOUSDT', 'ONEUSDT', 'OPUSDT', 'ORDERUSDT', 'ORDIUSDT', 'ORTUSDT', 'PAALUSDT',
    'PARTIUSDT', 'PAWSUSDT', 'PELLUSDT', 'PENDLEUSDT', 'PENGUUSDT', 'PEOPLEUSDT', 'PEPEUSDT', 'PERPUSDT',
    'PINEYEUSDT', 'PIRATEUSDT', 'PIXFIUSDT', 'PLUMEUSDT', 'PNUTUSDT', 'POLUSDT', 'PONKEUSDT', 'POPCATUSDT',
    'PORT3USDT', 'PORTALSUSDT', 'PORTALUSDT', 'PRCLUSDT', 'PRIMEUSDT', 'PROVEUSDT', 'PSGUSDT', 'PSTAKEUSDT',
    'PUFFERUSDT', 'PUFFUSDT', 'PUMPBTCUSDT', 'PUMPUSDT', 'PURSEUSDT', 'PYTHUSDT', 'PYUSDUSDT', 'QNTUSDT',
    'QORPOUSDT', 'QTUMUSDT', 'RACAUSDT', 'RATSUSDT', 'RDNTUSDT', 'RECALLUSDT', 'REDUSDT', 'RENDERUSDT',
    'RESOLVUSDT', 'RLUSDUSDT', 'ROAMUSDT', 'ROOTUSDT', 'ROSEUSDT', 'RPLUSDT', 'RSS3USDT', 'RUNEUSDT',
    'RVNUSDT', 'SAFEUSDT', 'SAHARAUSDT', 'SANDUSDT', 'SAROSUSDT', 'SATSUSDT', 'SCAUSDT', 'SCRTUSDT',
    'SCRUSDT', 'SCUSDT', 'SDUSDT', 'SEIUSDT', 'SENDUSDT', 'SERAPHUSDT', 'SFUNDUSDT', 'SHARDSUSDT',
    'SHIBUSDT', 'SHRAPUSDT', 'SIDUSUSDT', 'SIGNUSDT', 'SISUSDT', 'SKATEUSDT', 'SKYUSDT', 'SLPUSDT',
    'SNXUSDT', 'SOLOUSDT', 'SOLUSDT', 'SOLVUSDT', 'SOMIUSDT', 'SONICUSDT', 'SOSOUSDT', 'SPECUSDT',
    'SPELLUSDT', 'SPKUSDT', 'SPXUSDT', 'SQDUSDT', 'SQRUSDT', 'SQTUSDT', 'SSVUSDT', 'STETHUSDT',
    'STOPUSDT', 'STREAMUSDT', 'STRKUSDT', 'STXUSDT', 'SUIUSDT', 'SUNDOGUSDT', 'SUNUSDT', 'SUPRAUSDT',
    'SUSDT', 'SUSHIUSDT', 'SVLUSDT', 'SWEATUSDT', 'SWELLUSDT', 'SXTUSDT', 'SYNDUSDT', 'TACUSDT',
    'TAIKOUSDT', 'TAIUSDT', 'TAUSDT', 'TELUSDT', 'THETAUSDT', 'TIAUSDT', 'TIMEUSDT', 'TNSRUSDT',
    'TOKENUSDT', 'TONUSDT', 'TOSHIUSDT', 'TOWNSUSDT', 'TRCUSDT', 'TREEUSDT', 'TRUMPUSDT', 'TRVLUSDT',
    'TRXUSDT', 'TSLAXUSDT', 'TUNAUSDT', 'TURBOSUSDT', 'TUSDUSDT', 'TWTUSDT', 'ULTIUSDT', 'UMAUSDT',
    'UNIUSDT', 'USD1USDT', 'USDCUSDT', 'USDDUSDT', 'USDEUSDT', 'USDQUSDT', 'USDRUSDT', 'USDTBUSDT',
    'USDYUSDT', 'USTCUSDT', 'UUSDT', 'UXLINKUSDT', 'VANAUSDT', 'VANRYUSDT', 'VELOUSDT', 'VENOMUSDT',
    'VETUSDT', 'VICUSDT', 'VINUUSDT', 'VIRTUALUSDT', 'VRAUSDT', 'VTHOUSDT', 'VVVUSDT', 'WALUSDT',
    'WAVESUSDT', 'WAXPUSDT', 'WBTCUSDT', 'WCTUSDT', 'WEMIXUSDT', 'WENUSDT', 'WIFUSDT', 'WLDUSDT',
    'WLFIUSDT', 'WOOUSDT', 'WUSDT', 'XAIUSDT', 'XANUSDT', 'XAUTUSDT', 'XAVAUSDT', 'XCADUSDT',
    'XDCUSDT', 'XECUSDT', 'XEMUSDT', 'XIONUSDT', 'XLMUSDT', 'XOUSDT', 'XPLUSDT', 'XRPUSDT',
    'XTERUSDT', 'XTZUSDT', 'XUSDT', 'XUSDUSDT', 'YBUSDT', 'YFIUSDT', 'ZBTUSDT', 'ZENTUSDT',
    'ZENUSDT', 'ZEREBROUSDT', 'ZEROUSDT', 'ZETAUSDT', 'ZEXUSDT', 'ZIGUSDT', 'ZILUSDT', 'ZKCUSDT',
    'ZKJUSDT', 'ZKLUSDT', 'ZKUSDT', 'ZORAUSDT', 'ZRCUSDT', 'ZROUSDT', 'ZRXUSDT', 'ZTXUSDT',
    ]
